package org.haven.reporting.infrastructure.persistence;

import org.haven.reporting.domain.ExportAuditMetadata;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Repository for ExportAuditMetadata
 * Provides query methods for compliance reporting and retention management
 */
@Repository
public interface ExportAuditMetadataRepository extends JpaRepository<ExportAuditMetadata, UUID> {

    /**
     * Find audit metadata by export job ID
     */
    Optional<ExportAuditMetadata> findByExportJobId(UUID exportJobId);

    /**
     * Find exports generated by a specific user
     */
    List<ExportAuditMetadata> findByRequestedByUserIdOrderByGeneratedAtDesc(UUID userId);

    /**
     * Find exports within a date range
     */
    @Query("SELECT e FROM ExportAuditMetadata e WHERE e.generatedAt >= :startDate AND e.generatedAt <= :endDate ORDER BY e.generatedAt DESC")
    List<ExportAuditMetadata> findByGeneratedAtBetween(
            @Param("startDate") Instant startDate,
            @Param("endDate") Instant endDate);

    /**
     * Find exports overlapping a reporting period
     */
    @Query("SELECT e FROM ExportAuditMetadata e WHERE e.reportingPeriodStart <= :periodEnd AND e.reportingPeriodEnd >= :periodStart ORDER BY e.generatedAt DESC")
    List<ExportAuditMetadata> findByReportingPeriodOverlapping(
            @Param("periodStart") LocalDate periodStart,
            @Param("periodEnd") LocalDate periodEnd);

    /**
     * Find exports by CoC code
     */
    List<ExportAuditMetadata> findByCocCodeOrderByGeneratedAtDesc(String cocCode);

    /**
     * Find expired exports for retention policy cleanup
     */
    @Query("SELECT e FROM ExportAuditMetadata e WHERE e.expiresAt IS NOT NULL AND e.expiresAt <= :now")
    List<ExportAuditMetadata> findExpiredExports(@Param("now") Instant now);

    /**
     * Count exports by user in a time period (for rate limiting)
     */
    @Query("SELECT COUNT(e) FROM ExportAuditMetadata e WHERE e.requestedByUserId = :userId AND e.generatedAt >= :since")
    long countByUserSince(@Param("userId") UUID userId, @Param("since") Instant since);
}
